# Generated by Django 4.2.10 on 2024-02-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_bagages_car_customeruser_driver_seats_seats_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeruser",
            name="seats",
        ),
    ]
