# Generated by Django 4.2.10 on 2024-02-20 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_customeruser_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagages',
            name='bagage_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bagages',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bagages',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.customeruser'),
        ),
        migrations.AddField(
            model_name='bagages',
            name='descripion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bagages',
            name='weigth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='destination',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='destination',
            name='end_at',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='start_at',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bagages',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
