# Generated by Django 4.2.10 on 2024-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_car_bagages_remove_car_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='seats',
            field=models.ManyToManyField(to='common.seats'),
        ),
    ]
